run:
	python3 Query1/mapper.py |sort|python3 Query1/reducer.py >Query1/result.txt
	python3 Query2/mapper.py |sort|python3 Query2/reducer.py >Query2/result.txt
	python3 Query3/mapper.py |sort|python3 Query3/reducer.py >Query3/result.txt
	python3 Query4/mapper.py |sort|python3 Query4/reducer.py >Query4/result.txt
	python3 Query5/mapper.py |sort|python3 Query5/reducer.py >Query5/result.txt